### ISSUE TITLE
information disappeared after new release

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-theme-tugraz#153]
on the front page the author is not more displayed
![frontpage_item_author_missing](https://user-images.githubusercontent.com/216565/106814609-f3f29b80-6672-11eb-97b7-e05058e376df.png)

on the search page the author and the access rights are gone
![search_item_author_and_permission_missing](https://user-images.githubusercontent.com/216565/106814613-f5bc5f00-6672-11eb-9a63-44243fd73bb5.png)

**Comment by mb-wali** [comment]
closed with #154
