### ISSUE TITLE
move from setup.py to setup.cfg

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-theme-tugraz#259]
see [commit](https://github.com/inveniosoftware/invenio-app-rdm/commit/cf98c7161d2d78cd5c1d16d67ac42fe42fa0ba9e) for a reference.

**Comment by utnapischtim** [comment]
see https://github.com/tu-graz-library/invenio-imoox/blob/main/setup.cfg

**Comment by utnapischtim** [comment]
closed with 4fd0501c580f2c108795b398ee7888ac435f9768
