### ISSUE TITLE
badge label colors

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-theme-tugraz#59]
* Publication Date
* Resource Type
* access_right
...

Choose colors that match the TU Graz theme. available semantic UI colors as below:
```
@primaryColor   : @pink;
@secondaryColor : @grey;
@red            : #B03060;
@orange         : #FE9A76;
@yellow         : #FFD700;
@olive          : #32CD32;
@green          : #016936;
@teal           : #008080;
@blue           : #0E6EB8;
@violet         : #EE82EE;
@purple         : #B413EC;
@pink           : #FF1493;
@brown          : #A52A2A;
@grey           : #A0A0A0;
@black          : #000000;
```
if none above then should be overridden.
open discussion @utnapischtim

**Comment by utnapischtim** [comment]
please change the version badge as in the screenshot, except remove the pipe

**Comment by mb-wali** [comment]
The badges - color and style should be the same - as for **Frontpage** and **Search page**.
