### ISSUE TITLE
License should be displayed more prominent

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-theme-tugraz#84]
the problem is: in this screenshot it is visible that a user has to scroll down to see the license. That should not be. Therefore the license information should be put more prominently. Maybe as a badge or somewhere else, we have to discuss where it is the best place by creating some screenshots with different solutions. improve #98 

![license_should_be_more_up](https://user-images.githubusercontent.com/216565/93461434-08611200-f8e5-11ea-8081-70dbacee22b1.png)

**Comment by mb-wali** [comment]
@utnapischtim  is this still open issue for you?
