### ISSUE TITLE
export should be converted to a drop-down list

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-theme-tugraz#85]
Now it is displayed as a list. It should be a drop-down list and if the user would click on a item it would do the same as now, clicking on a list item. improve #98 

![export_converted_to_dropdown](https://user-images.githubusercontent.com/216565/93461780-8e7d5880-f8e5-11ea-9053-b9f27b9c0820.png)

**Comment by mb-wali** [comment]
Closing since it's not valid anymore.
