### ISSUE TITLE
The field requirement marked should be the same on all pages

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-theme-tugraz#89]
On the deposit page the required fields are marked with a asterisk. On the community page there is a tooltip below of the field to indicate that it is required written as a text message.
![required_marked_with_asterisk](https://user-images.githubusercontent.com/216565/93581247-2b50fc00-f9a1-11ea-85fb-94504f5a75be.png)
![required_marked_with_required_underline_tooltip](https://user-images.githubusercontent.com/216565/93581251-2be99280-f9a1-11ea-8894-8880e256d1aa.png)

**Comment by mb-wali** [comment]
this is not apart of this module. since invenio-theme-tugraz is not overriding the deposit page yet.
