### ISSUE TITLE
apply tugraz theme layout style to the record landing page

### ISSUE THREAD

**Issue by utnapischtim** [tu-graz-library/invenio-theme-tugraz#98]
The record should look like the following screenshot. It is already implemented but not in use yet. The config.py has to override the RECORDS_UI_ENDPOINTS coming from invenio_rdm_records.config

I will create further issues. This is not the final version. The next issues will reference this one.

![repository_record](https://user-images.githubusercontent.com/216565/94801690-b3de8c00-03e6-11eb-9fed-0f52b373158f.png)

**Comment by mb-wali** [comment]
Closed by #141
